//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace meowlabel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sk-proj-UWeZDZ4EOYjrBiPRCZ7JDrnfolXLy59iafHhX8PrQIoO38VodBvZZQ9BnyBL8BbaopTSN0532" +
            "hT3BlbkFJgqdCAcQDqm4tNY0mD9iqEISC3ZQJ_2-wcKv0FUhfOkfHbxlTvYw_7gyVdwbmt9dds7EMtNR" +
            "ckA")]
        public string OPENAI_API_KEY {
            get {
                return ((string)(this["OPENAI_API_KEY"]));
            }
            set {
                this["OPENAI_API_KEY"] = value;
            }
        }
    }
}
